Implement bootstrap components
craftercms/bootstrap-blueprint pull request #2
Opened 2021-12-06 22:54 UTC by jvega190

2021-12-07 13:51 UTC, rart requested changes
- Add sensible defaults to all relevant fields on the content type definition
- Every component should declare a root tag
- Be consistent in the use of fallbacks (e.g. ´!''´)
- Add conditional empty classes to all text fields

2021-12-07 13:51 UTC, rart commented on config/studio/content-types/component/badge/form-definition.xml
> +	<imageThumbnail>undefined</imageThumbnail>
Remove lo these undefined values.
Please create a bug to fix this on studio.

2021-12-07 13:51 UTC, rart commented on templates/web/accordion.ftl
> +<#import "/templates/system/common/crafter.ftl" as crafter />
No root tag

2021-12-07 13:51 UTC, rart commented on templates/web/accordion.ftl
> +        ${item.body_html!''}
make this into a node selector

2021-12-07 13:51 UTC, rart commented on templates/web/accordion.ftl
> +      No items have been added to the accordion.
Don't think this is necessary anymore. Use the system's empty classes (see usage on the older components)

2021-12-07 13:51 UTC, rart commented on templates/web/accordion.ftl
> +      window.addEventListener('DOMContentLoaded', () => {
This is not scoped to this component. If several accordions would be on the page, it would run multiple times for each accordion. Perhaps best to extract to a external script and put it on body_bottom.

This applies to all components.

2021-12-07 13:51 UTC, rart commented on templates/web/alert.ftl
> +  .crafter-alert span >  p {
don't use the word "crafter" in any "public" classes. Avoid leaking information on the final sites.

2021-12-07 13:51 UTC, rart commented on templates/web/alert.ftl
> +    margin-bottom: 0;
This style is suspicious. Doesn't look like something we should be doing. Avoid style overrides or things that modify how bootstrap behaves.

2021-12-07 13:51 UTC, rart commented on templates/web/alert.ftl
> +  id="alert-${contentModel.objectId}"
Doesn't seem to be in use (the id)

2021-12-07 13:51 UTC, rart commented on templates/web/badge.ftl
> +  ${contentModel.content_s!''}
Missing field tag

2021-12-07 13:51 UTC, rart commented on templates/web/breadcrumb.ftl
> +<@crafter.breadcrumb
Missing component root tag

2021-12-07 13:51 UTC, rart commented on templates/web/button.ftl
> +    ${contentModel.text_s!'Button'}
remove fallback text and conditionally add empty class

2021-12-07 13:54 UTC, rart commented
Review the older components on their use of empty classes freshen up around the most recent list of ice macros you have available.

2021-12-07 22:01 UTC, jvega190 commented on config/studio/content-types/component/badge/form-definition.xml
> +	<imageThumbnail>undefined</imageThumbnail>
Bug created https://github.com/craftercms/craftercms/issues/5140

2021-12-16 15:07 UTC, jvega190 commented
Closing this PR in favor of https://github.com/craftercms/bootstrap-blueprint/pull/3

2021-12-16 15:07 UTC, closed without merging

2021-12-16 17:30 UTC, jvega190 commented on templates/web/card.ftl
> +<@crafter.div class="card" style="width: 18rem;">
Already removed in 'components' branch